# Generated by Django 5.1.2 on 2024-11-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reportedmovie',
            options={'ordering': ['-created_at']},
        ),
    ]
